### ISSUE TITLE
I need help troubleshooting with @auth/core

### ISSUE THREAD

**Issue by bbigras** [wmalarski/qwik-next-auth-example#8]
I want to debug with a local checked out https://github.com/nextauthjs/next-auth.git.

I tried:

```sh
cd ~/src/next-auth
pnpm install

cd ~/src/next-auth/packages/core
pnpm build

cd ~/src/next-auth
npm link

# in my project
npm uninstall @auth/core
npm link @auth/core
```

My project then seem to use the code from `~/src/next-auth`, but I got some `__vite_ssr_import_0__.renderToString is not a function` errors.

Do you use something similar?

**Comment by wmalarski** [comment]
Nah, I didn't pull the local version of `auth.js`. I just used a browser built-in debugger and I modified files in node_modules to check things.

**Comment by bbigras** [comment]
Thanks!
